# Generated by Django 6.0.2 on 2026-02-16 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_bill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['paid', 'due_date', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='idx_bill_user_status',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='status',
            new_name='paid',
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'paid'], name='idx_bill_user_paid'),
        ),
    ]
