"""
WSGI config for budget_tracker project.

This file is used when the project is served with a traditional WSGI web
server. For a beginner project, you usually do not edit this file often, but
it is still an important part of how Django starts.
"""

import os

from django.core.wsgi import get_wsgi_application

# Point Django to the settings file for this project.
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'budget_tracker.settings')

# `application` is the WSGI callable the server looks for when starting up.
application = get_wsgi_application()
